services:
  lieferspatz:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "app"
    volumes:
      - .:/app
    environment:
      FLASK_APP: "src:app"
      FLASK_DEBUG: "true"
      FLAST_PORT: "5000"
    restart: on-failure
    ports:
      - "8000:5000"
