from .Account import Account
from .Customer import Customer
from .Restaurant import Restaurant
from .Order import Order
from .Menu import Menu
from .MenuItem import MenuItem
from .OpeningHour import OpeningHour
from .PostalCode import PostalCode
from .PostalCodeRestaurant import PostalCodeRestaurant
